#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th iteration using while and if

counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
