#!/usr/bin/env bash
# Check if running in Docker (check for the presence of /.dockerenv)
if [ -f /.dockerenv ]; then
    # Modify /etc/hosts file
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
    echo "Hosts file updated successfully."
else
    echo "This script is meant to run in Docker. Aborting."
fi
