#!/usr/bin/env bash
# Using ifconfig to get IPv4 addresses including localhost
ipv4_addresses=$(ifconfig | awk '/inet / {gsub("addr:","",$2); print $2}')

# Displaying active IPv4 addresses
echo "Active IPv4 addresses on this machine:"
echo "$ipv4_addresses"
