#!/usr/bin/env bash

# Using hostname and grep to get IPv4 addresses
ipv4_addresses=$(hostname -I | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$')

# Displaying active IPv4 addresses
echo "Active IPv4 addresses on this machine:"
echo "$ipv4_addresses"
